[formatting]
column_width = 90
compact_arrays = true

[[rule]]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "workspace.dependencies",
  "formatting",
]

[rule.formatting]
reorder_keys = true
