[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
distributor = "5YP6jdWGTNDUhLYMCfocbyfT4RN58QbhVdtYmBdL6Af1"

[programs.devnet]
distributor = "5YP6jdWGTNDUhLYMCfocbyfT4RN58QbhVdtYmBdL6Af1"

[programs.mainnet]
distributor = "5YP6jdWGTNDUhLYMCfocbyfT4RN58QbhVdtYmBdL6Af1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

deposit = "yarn run ts-node app/deposit.ts"
generate = "yarn run ts-node app/generateMarkerHolders.ts"
